openapi: 3.0.1
info:
  title: Ishan Test Webhooks
  description: well i'm just trying something lol234556
  x-cortex-git:
    github:
      repository: cortextests/ishan-test-webhooks
  x-cortex-tag: ishan-test-webhooks
  x-cortex-type: service
