openapi: 3.0.1
info:
  title: Ishan Test Webhooks223
  description: well i'm just trying something lol
  x-cortex-git:
    github:
      repository: cortextests/ishan-test-webhooks
  x-cortex-tag: ishan-test-webhooks2
  x-cortex-type: service
